### ISSUE TITLE
support giving a file name

### ISSUE THREAD

**Issue by ryanking** [kisielk/errcheck#106]
I would love to use errcheck as a linter, but for that I need to be able to supply a filename rather than a module. Would you consider supporting that?

**Comment by kisielk** [comment]
I'm not sure that would work. errcheck relies on `go/types` and `go/build` to analyze the code and generally that requires the entire entire package.

**Comment by dominikh** [comment]
We could determine the package based on the file name, type check the whole package but only lint the provided file.

**Comment by kisielk** [comment]
Ah ok, that seems reasonable. I don't think it would be too hard to add. Do you know how to find a package given a filename?

**Comment by shurcooL** [comment]
> Do you know how to find a package given a filename?

Yes:

https://github.com/shurcooL/play/blob/456f0172d733e4e6730f290ed042849370c132a7/200/cmd/importpathof/main.go#L93-L103

**Comment by kisielk** [comment]
Great, thanks. I figured this was something someone would have solved
already :) I'll try to whip up a patch some time soon

**Comment by shurcooL** [comment]
> I would love to use errcheck as a linter, but for that I need to be able to supply a filename rather than a module.

I have a question. Why can't a linter be used on an entire package at once? Why does it need to work on a single filename at a time?

For example, when I use `golint` in the terminal, I just run it on the entire package. What am I missing? Is it for running those linters inside an editor?

**Comment by ryanking** [comment]
@shurcooL because the linting framework I use does a file at a time

**Comment by ryanking** [comment]
@kisielk it seems that golint already handles this well:

https://github.com/golang/lint/blob/master/golint/golint.go

**Comment by shurcooL** [comment]
> @shurcooL because the linting framework I use does a file at a time

I see.

**Comment by sandro** [comment]
Hi 👋
Any updates on this?
