### ISSUE TITLE
Support ignoring vendor folder

### ISSUE THREAD

**Issue by Wen777** [kisielk/errcheck#111]
Since go has 1.7 version, it supports *vendor* folder for version control. However, a golang project depends on different packages and those packages don't handle error well. It would be very good if errcheck allow developers to ignore vendor folder(dependencies) and let developers focus on their own code.

![screenshot from 2016-09-30 22 21 43](https://cloud.githubusercontent.com/assets/7497207/18994859/4de77598-875c-11e6-92f4-302ddb06bbb9.png)

**Comment by shurcooL** [comment]
See https://github.com/kisielk/errcheck/issues/96#issuecomment-192196026.

This issue has come up before, and the standard way of doing this is by using an external tool. E.g.:

```
errcheck $(go list ./... | grep -v /vendor/)
```

**Comment by Wen777** [comment]
@shurcooL Great command ! Thanks.
