### ISSUE TITLE
allow ignoring methods on specific types

### ISSUE THREAD

**Issue by tamird** [kisielk/errcheck#112]
For instance, database/sql has a Close() method on `*Rows`, `*DB`, and `*Stmt`. It is not currently possible to ignore one of these without ignoring the others.

cc @andreimatei

**Comment by kisielk** [comment]
I think I will extend what's been done in #115 and allow the list to be modified via an input file so that specific types can be ignored. Then we'll deprecate the existing regexp based ignore facility.

**Comment by dominikh** [comment]
I'd lean towards a flag, not a file; mainly because a file can easily be turned into a flag (via `$(cat ...)`), but the inverse isn't quite as easy.

**Comment by kisielk** [comment]
Isn't there a limit to the size of an argument string that can be passed to a process?

**Comment by dominikh** [comment]
POSIX requires a minimum of 4KiB for the entire argument string. Linux has a minimum of 128 KiB, but it can be higher (1/4th of the stack size). Old Cygwin had 30KB, I don't expect it to be lower now. OS X and modern FreeBSD both allow 256 KiB. Windows is stuck at a low 8 KiB.[[1]](http://www.in-ulm.de/~mascheck/various/argmax/) [[2]](https://support.microsoft.com/en-us/kb/830473)

POSIX suggests leaving 2 KiB of headroom for the manipulation of environment variables, we'll apply the same to Windows as it handles env vars in a similar way. That leaves us with the following conservative limits, assuming 90 characters per ignored method + newline separator

| System        | Limit |
|---------------|-------|
| POSIX         |    22 |
| Windows       |    68 |
| Cygwin        |   333 |
| Linux         |  1433 |
| OS X, FreeBSD |  2889 |


The POSIX limit is not relevant on any modern systems that we need to support. The Windows limit might indeed be a problem (one that staticcheck and gosimple currently have, as they allow ignoring checks via a command line argument)

**Comment by kisielk** [comment]
That seems like it may be okay, though the limit for Windows seems like a bit on the low side. The bigger concern is with editor and other linter integration. It seems easier to have a flag that can just point to a file committed in your project repository than to figure out how to get your toolchain to open the file and pass its contents as an argument to errcheck.

**Comment by dominikh** [comment]
I'm absolutely undecided here. I'd prefer if we didn't have ten different ways of ignoring things, but each tool has their own already, anyway. I'm leaving that decision up to you.

**Comment by kisielk** [comment]
What do you mean by 10 different ways of ignoring things? In this one tool or between different tools?

**Comment by dominikh** [comment]
Sorry, I phrased that somewhat ambiguously. I meant between tools. And I exaggerated somewhat.

My tools have their CLI based ignoring, gometalinter has some regexp based filtering, the Go tools require you to apply `grep -v` or some other form of manual filtering. But I guess it doesn't matter in the end.

**Comment by kisielk** [comment]
The main reason I like this method of filtering as opposed to grep or regexp is that it is more precise, less of a chance of filtering out something you did not intend.
