### ISSUE TITLE
Allow comment to suppress complaints

### ISSUE THREAD

**Issue by doherty** [kisielk/errcheck#114]
If the code author knows that an error is safe to be ignored, they may omit the return, or assign to underscore, either of which could be caught by errcheck (with `-blank` in the latter case). It'd be nice if the author could add a comment that would cause errcheck to skip complaining:
```go
v, _ = cannotFail() // errcheck: this thing can't ever fail, so it's ok to assign to _
```
This is comparable to "nolint" comments and such in other programming languages.

**Comment by shurcooL** [comment]
This has been suggested and discussed in the past a couple of times (but I couldn't find any issue that was directly about this, so this isn't a duplicate).

For example, see https://github.com/kisielk/errcheck/issues/101#issuecomment-232073505 and the discussion below.

The conclusion, so far, has been that it's a bad idea to add comment directives that let you do this. Instead, a better solution is to always handle errors. If an error cannot happen, the API should be modified to not return an error. And standard library methods that are documented and known not to fail should be exceptions built in to `errcheck`.

**Comment by doherty** [comment]
Putting these annotations in code is superior to using `-ignore` because it is the author of the code who knows whether the check should be skipped -- not the operator of the `errcheck` tool.

If you really want to amass a global whitelist, I guess we can start doing that. [`"math/rand".Read()`](https://godoc.org/math/rand#Read) and its method counterpart always returns a nil error.

**Comment by kisielk** [comment]
I like the idea of a global whitelist. I'm not sure how to implement it exactly. I suppose a map of package->function / type.Method. I think the right place to put the check would be in `ignoreCall` but it's been a long time since I've played with the types package and I don't remember how to figure out if something is a method or not and what type it belongs to.

**Comment by dominikh** [comment]
A method call in the AST is an *ast.CallExpr where CallExpr.Fun is an *ast.SelectorExpr. SelectorExpr.X is your receiver (one of *ast.Ident, *ast.CompositeLit or another *ast.SelectorExpr, but it doesn't matter, TypeOf(X) will get you the type in all cases), and SelectorExpr.Sel is an *ast.Ident, which you can turn into a *types.Object via ObjectOf.

**Comment by kisielk** [comment]
Ok. I think it's staring to make sense again. One thing I don't understand is why `TypeOf` returns a `*types.Basic` for packages. eg: if you have an expression like `fmt.Println` then `TypeOf(exp.X)`v gives a `*types.Basic` which prints to `"invalid type"`

But basically my idea is to have a collection keyed on the string returned by `TypeOf` and the Name field of `ObjectOf` to check each expression.

**Comment by dominikh** [comment]
@kisielk Would you like me to take a stab at it, or have you already started working on it?

**Comment by kisielk** [comment]
@dominikh feel free, I haven't done anything other than become familiar with some of the ast code again :)

**Comment by kisielk** [comment]
Actually I just realized #107 kind of does this, but it's not complete and I'm not sure if the method it's using is valid.

**Comment by dominikh** [comment]
@kisielk I am almost done with a prototype that I'll PR soon (within the hour most likely)

**Comment by dominikh** [comment]
#115 for a WIP PR.

**Comment by v2ray** [comment]
+1 for adding per-line suppression.

The purpose for using a linter is to detect all possible issues in the code, and fix them one by one. The global whitelist may be abused, and leads to a wider range of suppression. It is essentially the same as switching off the linter completely.

I understand your concern on per-line suppression. Just want to say that global whitelist is not better at all.

**Comment by kisielk** [comment]
The global whitelist is indeed switching off the linter, for functions in the whitelist. 

I am still against adding any kind of suppression comments. I don't think source code should adapt to appease tools. Also comments are often ignored or not updated when changing code, which could lead to ignoring things which were not intended. It's also impossible to know at a glance what the tool is ignoring without inspecting all the source code in a project. The whitelist gives you one place to look.

**Comment by v2ray** [comment]
>  Also comments are often ignored or not updated when changing code, which could lead to ignoring things which were not intended.

Same applies to the whitelist.

There is a strong motivation to add a function to the whitelist (in order to suppress warnings), but there is no such motivation to regularly check the list and remove out-dated ones. There is no mechanism to get notified for behavior change of a function. As long as a function declare to return error, it may return error at a certain time. The only way to tell whether a function fits the whitelist is to read its doc or even source code. It becomes highly time consuming to do so when the whitelist grows to say 100 functions. The whitelist will be definitely abused in the long run.

I don't think such kind of human error is preventable by a tool itself. It is more of the responsibility of a policy or development workflow. As for the tool, it should provide flexibility for users to decide the way that suits their workflow best.

**Comment by kisielk** [comment]
Well, the purpose of the whitelist is entirely different. It's so you can whitelist functions where the error never needs to be checked. For example the `Write` method of `bytes.Buffer`. If you want to ignore a particular instance of an error, you can always assign it to the blank identifier and leave a comment. That's just as good as placing directives for the linter but without being specific to it.

**Comment by doherty** [comment]
Please also keep in mind that not all code is public, so adding it to some whitelist in errcheck's codebase is not going to fly for those users. This effectively means they cannot use errcheck.

**Comment by dominikh** [comment]
> Please also keep in mind that not all code is public, so adding it to some whitelist in errcheck's codebase is not going to fly for those users. This effectively means they cannot use errcheck.

@doherty The whitelist can be extended by the user by providing a file with the appropriate patterns. You'd check in a file with those rules into your repository and use said file when invoking errcheck. There is no need to add these rules to errcheck's code base.
