### ISSUE TITLE
Rewrite in terms of lintutil

### ISSUE THREAD

**Issue by tamird** [kisielk/errcheck#117]
https://godoc.org/honnef.co/go/lint/lintutil is a neat package by @dominikh that provides a framework for writing linters like errcheck.

The main benefit of rewriting errcheck in terms of lintutil is that it would allow users to implement "meta linters" that can run many lints while traversing the AST only once. Such a thing already exists in CockroachDB (https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/metacheck/main.go).

cc @dominikh

**Comment by dominikh** [comment]
I would hold off on that at least for now, as the API of lintutil is not stable yet and going to change in the near future.

(And, to be pedantic: the AST will still be traversed lots of times. your meta linter avoids the cost of parsing, type checking and SSA building)

**Comment by tamird** [comment]
Fair enough, thanks for the correction. FWIW, the meta linter saves about
80% of the time-cost of each linter that is added to it (in my testing
against CockroachDB).

**Comment by dominikh** [comment]
Frankly, at this point, I'd prefer keeping lintutil internal, as I will experiment with alternative/forked SSA packages and the like, so it won't really be fit for general projects for now.

**Comment by zimmski** [comment]
@dominikh: Since we are doing pretty much the same thing as your lint project internally and we have also implemented such a meta-linter as described in this issue, I would be very interested in what you are working right now? Could you ping me via mail?

**Comment by dominikh** [comment]
@zimmski Sure, I've sent you an email.

**Comment by tamird** [comment]
Done in https://github.com/dominikh/go-tools/issues/23.
