### ISSUE TITLE
Repro for CGO errors on alpine

### ISSUE THREAD

**Issue by novas0x2a** [kisielk/errcheck#119]
I have an easy repro (and workaround) for the problem mentioned in https://github.com/kisielk/errcheck/issues/16#issuecomment-160808162 (which is also mentioned in https://github.com/alecthomas/gometalinter/issues/149) re: running errcheck in a CGO_ENABLED build on alpine.

```
mike@lusus:~> docker run --entrypoint sh -it golang:1.7.4-alpine
/go # ( apk update && apk add git ) &>/dev/null
/go # go get github.com/kisielk/errcheck github.com/alecthomas/gometalinter github.com/stretchr/testify/assert
/go # cd /go/src/github.com/alecthomas/gometalinter/
/go/src/github.com/alecthomas/gometalinter # gometalinter --enable-gc --deadline 40s --exclude vendor --skip vendor --disable-all --enable=errcheck ./...
/usr/local/go/src/net/lookup_unix.go:58:24:warning: error return value not checked (undeclared name: cgoLookupHost) (errcheck)
/usr/local/go/src/net/lookup_unix.go:70:24:warning: error return value not checked (undeclared name: cgoLookupIP) (errcheck)
/usr/local/go/src/net/lookup_unix.go:86:23:warning: error return value not checked (undeclared name: cgoLookupPort) (errcheck)
/usr/local/go/src/net/lookup_unix.go:95:24:warning: error return value not checked (undeclared name: cgoLookupCNAME) (errcheck)
/usr/local/go/src/net/lookup_unix.go:162:23:warning: error return value not checked (undeclared name: cgoLookupPTR) (errcheck)
/go/src/github.com/alecthomas/gometalinter # errcheck ./...
exec: "gcc": executable file not found in $PATH
cgo failed: [go tool cgo -objdir /tmp/net_C448012175 -- -I /tmp/net_C448012175 cgo_linux.go cgo_resnew.go cgo_socknew.go cgo_unix.go]: exit status 1
/usr/local/go/src/net/lookup_unix.go:58:24: undeclared name: cgoLookupHost
/usr/local/go/src/net/lookup_unix.go:70:24: undeclared name: cgoLookupIP
/usr/local/go/src/net/lookup_unix.go:86:23: undeclared name: cgoLookupPort
/usr/local/go/src/net/lookup_unix.go:95:24: undeclared name: cgoLookupCNAME
/usr/local/go/src/net/lookup_unix.go:162:23: undeclared name: cgoLookupPTR
error: failed to check packages: could not type check: couldn't load packages due to errors: net
```

The error's pretty inscrutable when run via GML but pretty obvious when run through errcheck directly. Now if I install gcc and musl-dev, the error is resolved:
```
/go/src/github.com/alecthomas/gometalinter # apk add gcc musl-dev &>/dev/null
/go/src/github.com/alecthomas/gometalinter # gometalinter --enable-gc --deadline 40s --exclude vendor --skip vendor --disable-all --enable=errcheck ./...
main.go:162:15:warning: error return value not checked (defer r.Close()) (errcheck)
regressiontests/support.go:48:20:warning: error return value not checked (defer os.RemoveAll(dir)) (errcheck)
regressiontests/support.go:53:17:warning: error return value not checked (defer os.Remove(w.Name())) (errcheck)
/go/src/github.com/alecthomas/gometalinter # errcheck ./... | head -n5
main.go:162:15: defer r.Close()
regressiontests/support.go:48:20:       defer os.RemoveAll(dir)
regressiontests/support.go:53:17:       defer os.Remove(w.Name())
vendor/src/github.com/HewlettPackard/gas/core/issue.go:68:11:   file.Seek(start, 0)
vendor/src/github.com/HewlettPackard/gas/core/issue.go:84:19:   defer file.Close()
```

So, the source of the error is actually that CGO is configured but kinda broken, and the fix is to install the compiler and the libc headers. I'm not actually sure if there's anything errcheck (or GML) can do about this, but I figured I'd open this to at least provide google fuel for the next poor soul who runs into the problem like I did.

**Comment by kisielk** [comment]
I think it's because go/loader expects to load a compiled version of the package and compiles it if it's not available. It seems like the installation of Go you have doesn't have a cgo-enabled net package and so it wants to compile it, which requires gcc. At least that's my guess based on the log output.

**Comment by kisielk** [comment]
I actually think this is a separate problem from #16

**Comment by novas0x2a** [comment]
Ah, just to clarify:
1) I don't think it's the same problem as #16, but it is the same problem as the one in the [comment on 16 by](https://github.com/kisielk/errcheck/issues/16#issuecomment-160808162) @amacneil which was the only reference I found to the same problem I ran into. (My issue here is a direct response to @zimmski's request for a repro).
2) I think your analysis is correct, I just wanted to raise the issue because this is actually the official go alpine image, so more people are likely to run into the same problem (and I wanted to give them a google reference to find). It's unlikely to be fixed in the official image, because it's very common for alpine images to lack gcc.
3) I don't think this is a bug in errcheck, but I figured I'd raise it here in case you could think of a better way to handle it.

**Comment by kisielk** [comment]
Right, I agree with all that. I don't think there's a better way to fix it. Really if you are developing anything with CGO code, you should have a copy of gcc available.

**Comment by leighmcculloch** [comment]
I'm seeing this happen on Ubuntu after installing the go from the official download page. My installation process is [here](https://github.com/leighmcculloch/devenv/blob/70bfc55d62e991adf1b5222f9e246f2b5d531995/setup-system/install-go/install-go.sh#L1-L14) and is simply a wget of go, then go get of errcheck. I'm attempting to run errcheck on a project that does not use CGO.

**Comment by roadrunner** [comment]
@leighmcculloch, same here for alpine images 

when not using cgo at all, it's sad to explicitly tell `disable cgo`

**Comment by leighmcculloch** [comment]
I'm now using Go1.9 on Ubuntu with revision b1445a9dd8285a50c6d1661d16f0a9ceb08125f7 of errcheck and I no longer have this issue.

**Comment by kisielk** [comment]
Closing since it seems this was resolved.
