### ISSUE TITLE
exclude vendor dir from matching `...`

### ISSUE THREAD

**Issue by omarkohl** [kisielk/errcheck#124]
I realize a similar feature was already proposed (and rejected) in #111 but now Go 1.9 changed the behavior of the Go tools such as "go test" and "go vet" to ignore the vendor directory when using triple dot (...) . See https://github.com/golang/go/issues/19090

How about doing the same thing for errcheck? It makes sense to have different Go tools behave similarly.

**Comment by dominikh** [comment]
Related: https://github.com/kisielk/gotool/issues/16

**Comment by kisielk** [comment]
Is this fixed as a result of the gotool change?

**Comment by shurcooL** [comment]
That's right. As of https://github.com/kisielk/gotool/issues/16 being resolved, `gotool` will not include `vendor` when expanding `...` on Go 1.9 and later.
