### ISSUE TITLE
Is it possible to check for re-assigned and unused error parameter?

### ISSUE THREAD

**Issue by shhsu** [kisielk/errcheck#125]
Hey, here's a body of a method I encountered

```go
var1, err := foo1()
// forgot to check for error

// say that var2 is assigned in a if statement, anonymous function or loop, and need to be declared ahead of time
var var2 someType 
// ...
var2, err = foo2()  // can't do := because both var2 and err had been declared
```

errcheck is unable to pick this up as an error as of now. Is it possible to ensure err being used before it's assigned to another value?

**Comment by shurcooL** [comment]
`staticcheck` already detects this. (/cc @dominikh.)

```
main.go:6:8: this value of err is never used (SA4006)
```

Tested on [this program](https://play.golang.org/p/9grDz87mrG).

https://staticcheck.io/docs/staticcheck#checks:

> SA4006 - A value assigned to a variable is never read before being overwritten. Forgotten error check or dead code?

**Comment by shhsu** [comment]
Thanks!
