### ISSUE TITLE
errcheck : Command not found 

### ISSUE THREAD

**Issue by thaolinhvu** [kisielk/errcheck#126]
Hello,
I am still a beginner and hope you can help me, after not finding a solution in the the other issues.

I want to compile go-bindata, but it fails. 

make[1]: errcheck: Command not found
Makefile:7: recipe for target 'out/compress-nomemcopy.checked' failed
make[1]: *** [out/compress-nomecopy.checked] Error 127

After viewing the Makefile, I notice that I cannot run errcheck, how it is described in the readme file.
When I enter 
$ errcheck all 
it will say that the command cannot be found. That happens too, if I enter all the other commands, which are explained in the readme.

I tried to compile it with ./errcheck in the directory and it works only there with testdata. So I think I installed everything right.

How can I use errcheck? How does the syntax look like when I want to a give specific directory to be checked as an argument?

Thank you !

**Comment by kisielk** [comment]
If the command in the Makefile is just `errcheck` then you need to make sure the binary is in one of the paths pointed to by the `PATH` environment variable.

**Comment by thaolinhvu** [comment]
Thank you very much !
