### ISSUE TITLE
skip processing generated code

### ISSUE THREAD

**Issue by glasser** [kisielk/errcheck#131]
There is now a "standard" header for generated code and an increasing number of tools know about it.  It would be great if errcheck ignored those files.

https://golang.org/s/generatedcode

**Comment by kisielk** [comment]
I agree, if the behaviour is controllable via a flag that's off by default. I don't really have time to work on this at the moment so if you'd like to see the feature included please submit a PR.

**Comment by shurcooL** [comment]
> I agree, if the behaviour is controllable via a flag that's off by default.

👍

> if you'd like to see the feature included please submit a PR.

In case it's helpful, there's a Go implementation of a parser for the [golang.org/s/generatedcode](https://golang.org/s/generatedcode) comment available at https://godoc.org/github.com/shurcooL/go/generated.
