### ISSUE TITLE
Tag and release a stable version (1.0?)

### ISSUE THREAD

**Issue by mcandre** [kisielk/errcheck#134]
Thank you for publishing your wonderfully helpful errcheck system for identifying sensitive Go code! Could we get a git tag and release version, say v1.0, for this project? That way, developers can have confidence that they are using a specific version of errcheck, in case of any future changes that might break backwards compatibility.

**Comment by kisielk** [comment]
Definitely. It’s long overdue. Will do that soon.

**Comment by kisielk** [comment]
v1.0.0 has been tagges
