### ISSUE TITLE
ignore strings.Builder.WriteString

### ISSUE THREAD

**Issue by kevinburke** [kisielk/errcheck#136]
strings.Builder.WriteString always returns a nil error, per the documentation:

```
WriteString appends the contents of s to b's buffer. It returns the length of s and a nil error. 
```

via https://godoc.org/strings#Builder.WriteString.

Currently, errcheck flags me for not checking the error there.

**Comment by kevinburke** [comment]
Oh, yuck, I think my CI environment may have cached an old version of errcheck.

**Comment by kisielk** [comment]
No problem. I just tagged v1.0.1 as well to include that fix.
