### ISSUE TITLE
Example of ignoring functions outside standard library

### ISSUE THREAD

**Issue by alexflint** [kisielk/errcheck#139]
I am attempting to add the function "Println" in the package github.com/kr/pretty to my errcheck ignore file. However, none of the following lines result in the error being excluded:

```
github.com/kr/pretty.Println
"github.com/kr/pretty".Println
(github.com/kr/pretty).Println
("github.com/kr/pretty").Println
pretty.Println
```

The command I'm using is (and I can successfully ignore other functions inside the standard library):
```
errcheck -exclude .lint/errcheck-excludes src.go
```

The error I see is:
```
src.go:37:16:	pretty.Println(r)
```

The function signature is:
```
func Println(a ...interface{}) (n int, errno error)
```

**Comment by kisielk** [comment]
hm, maybe it would be useful if there was a flag for also printing the function name alongside the line so that it was easier to make the excludes.

**Comment by tymonx** [comment]
I have a similar issue with that. The `-v` is not present and the `-verbose` flag is not useful. I cannot get how to properly exclude some methods.
