### ISSUE TITLE
should not by default allow ignoring an error from fmt.Fprintf

### ISSUE THREAD

**Issue by nhooyr** [kisielk/errcheck#140]
fmt.Fprintf can be used with any reader and such a reader could potentially error.

**Comment by kisielk** [comment]
errcheck doesn't ignore errors from fmt.Fprintf by default

**Comment by nhooyr** [comment]
It does afaik? https://github.com/kisielk/errcheck/blob/8050dd7cc11578becd8622667107bb21a7baf451/main.go#L144

That matches all symbols in the fmt package.

**Comment by kisielk** [comment]
I think the only functions from that package that should be ignored are:

`fmt.Errorf`, `fmt.Print`, `fmt.Printf`, `fmt.Println`

**Comment by henvic** [comment]
@kisielk,

Any considerations on adding fmt.Fprint* when io.Writer = os.Stderr | os.Stdout to the ignore list?
