### ISSUE TITLE
errcheck *might* be reporting invalid errors in Fprintf() statements

### ISSUE THREAD

**Issue by shivansh** [kisielk/errcheck#143]
On updating to the recent version of errcheck, I've been encountering errors concerning `Fprintf()` statements.

One such instance -

```go
if err := parser.GenProductions(file); err != nil {
	fmt.Fprintf(os.Stderr, "%s", err)
	os.Exit(1)
}
```
For the above segment of code errcheck reports -
```
src/main.go:27:14:	fmt.Fprintf	fmt.Fprintf(os.Stderr, "%s", err)
```

I'm not sure I understand what might be wrong with the above print statement. Weirdly enough, similar errors are encountered when errcheck is run on its own source.

Any input will be appreciated.

**Comment by kisielk** [comment]
`fmt.Fprintf` can return an error, especially if the first argument is a file handle or network connection, hence errcheck reports unchecked errors on it.

You can either ignore specific cases by assigning the error to the blank identifier `_` or else you can add `fmt.Fprintf` to your ignore list if you never want to check it.

Prior versions of errcheck ignored all errors from functions in the `fmt` package by default, but this was recently changed.

**Comment by shivansh** [comment]
Ah, I see.
Thanks a lot!

**Comment by dominikh** [comment]
@leighmcculloch Definitely a good idea.

**Comment by shivansh** [comment]
@leighmcculloch 

This seems like a nice idea. Although I'm not sure it will be justified to impose such a restriction on users who do want a thorough error checking, including the print statements being described. I guess a better approach can be to add support for specifying statements like following in the ignore list -

```
fmt.Fprintf(os.Stderr, ...)  // syntax can be decided later
```

_I haven't checked whether errcheck already supports this._

This will be way better than the immediate workaround I used few days back, which was to ignore error checking entirely on all calls to `fmt.Fprintf()`.

**Comment by leighmcculloch** [comment]
I was initially thinking of just hardcoding that behavior, but you're right it really should be configurable. Doing it in a way that is configurable would require significantly more effort. I've decided to just address the issue with `_ =` in the project that was impacted and I'm going to abandon this issue as I don't think the effort to value is really there.
