### ISSUE TITLE
Please add an option to ignore errors using a comment in the source file

### ISSUE THREAD

**Issue by elad661** [kisielk/errcheck#144]
Hi,

I really liked errcheck, it looks like a very useful tool, thanks for making it!

My codebase has a lot of errors that can be safely ignored, and others that were unchecked by mistake. Adding them all to the exclude file would be difficult work.

Would it be possible to add a functionality to indicate "I know what I'm doing" in a comment before a line with an unhanded error to make errcheck ignore it? `pycodestlye`, for example, supports adding a comment `# noqa` to lines you want to not be checked.

**Comment by alecthomas** [comment]
If you use gometalinter or golangci-lint (which include errcheck), they both support `// nolint: errcheck` directives.

**Comment by dominikh** [comment]
The real solution to this isn't to add magic comments that will be used on 1/4th of all method calls. The real solution is to emit fewer false positives. The built-in ignore patterns for the standard library are a good start, and my own errcheck (TBA) will approach the problem in a different way alltogether.
