### ISSUE TITLE
Could not import code (no metadata)

### ISSUE THREAD

**Issue by kixelated** [kisielk/errcheck#150]
Hey guys, my deploy script that runs `go get -u github.com/kisielk/errcheck` just broke. Heh of course there was a merge to master just 30 minutes ago.

I'm running go 1.10. This is an internal repository so I can't provide much additional information:

```
error: failed to check packages: errors while loading package brood/internal/cache_test [brood/internal/cache.test]: [brood/internal/cache/expires_test.go:10:2: could not import brood/internal/cache (no metadata for brood/internal/cache)]
```

My `_test.go` files declare `package cache_test` while the rest are `package cache`. I do this for blackbox testing and I haven't heard anything about modules deprecating them.

```
Test files that declare a package with the suffix "_test" will be compiled as a
separate package, and then linked and run with the main test binary
```

**Comment by dominikh** [comment]
#148 shouldn't have been merged like that. go/packages only fully works with the upcoming Go 1.11 and Go 1.10.4 – for earlier versions of Go, including the current 1.10.3, it uses a fallback. And that fallback doesn't fully support package tests.

**Comment by nbyarnell** [comment]
Normally I wouldn't verbally +1 this but this is a small project - I'm running Go 1.10.3 and I'm also experiencing failures with master.

**Comment by dominikh** [comment]
I have undone the merge to fix everyone's builds. I'll let @kisielk sort out the rest.
