### ISSUE TITLE
Incomplete support for go modules

### ISSUE THREAD

**Issue by kispaljr** [kisielk/errcheck#155]
I am trying to use `errcheck` outside of `$GOPATH` in a project using go modules, but it reports import problems. More precisely it reports that modules downloaded into `$GOPATH/pkg/mod` cannot find their imported dependencies, because `errcheck` is looking for them under `$GOROOT`/`$GOPATH`, instead of `$GOPATH/pkg/mod`.

```
> errcheck -abspath .\...

C:\src\go\pkg\mod\github.com\docker\distribution@v2.7.0-rc.0.0.20181002220433-1cb4180b1a5b+incompatible\blobs.go:13:2: could not import github.com/opencontainers/image-spec/specs-go/v1 (cannot find package "github.com/opencontainers/image-spec/specs-go/v1" in any of:
	C:\Go\src\github.com\opencontainers\image-spec\specs-go\v1 (from $GOROOT)
	C:\src\go\src\github.com\opencontainers\image-spec\specs-go\v1 (from $GOPATH))
```
I am using the latest commit in the master branch (`commit 1787c4b  on Aug 7`).

**Comment by domgreen** [comment]
Seems like the PR #148  has been reverted, probably as when checking out the commits it didnt build.

**Comment by tschellenbach** [comment]
+1

**Comment by peter-edge** [comment]
When can we get this un-reverted? :-)

**Comment by dominikh** [comment]
@kisielk

**Comment by nmiyake** [comment]
Can anyone provide context on why the previous PR was reverted/what needs to be done for it to get accepted? I didn't see any information on this in the revert commit. Is the fix noted at https://github.com/kisielk/errcheck/pull/148#issuecomment-434626770 sufficient, or are there larger issues that need to be addressed?

I'm interested in seeing this issue fixed and would be happy to contribute work towards doing so, but would like to verify the current state/plan before doing anything to ensure not to duplicate effort.

**Comment by coopernurse** [comment]
I built `errcheck` using @domgreen's fork here: https://github.com/domgreen/errcheck/commits/revert_and_fix and can confirm that fixed my issues with Go 1.11 modules.

I don't see an open PR for this branch though. I see this PR was closed: https://github.com/kisielk/errcheck/pull/156

Is there more work to do here?

**Comment by peter-edge** [comment]
A lot of us super appreciate the work that @kisielk has done here (and your work too, @dominikh) and we rely on it every day. Anything we can do to get this fixed ASAP would be great, it’s going to become a bigger and bigger issue as more people convert to Golang modules.

**Comment by peter-edge** [comment]
Speaking for myself, I have errcheck (and staticcheck, unused @dominikh) commented out in https://github.com/uber/prototool/blob/dev/Makefile which is not a state I want this repository to be in - errcheck and staticcheck specifically have saved me a bunch of times

**Comment by dominikh** [comment]
I can't speak for @kisielk, but if someone sends a working PR with proper go/packages support for errcheck, it'll likely get merged quickly.

Otherwise I can probably take a look at it myself after I've sorted out my own tools.

**Comment by coopernurse** [comment]
Cool, well I just opened this: https://github.com/kisielk/errcheck/pull/159 based on @domgreen's fork.  I removed the `vendor` dir and `errcheck` binary that he had committed, but otherwise it's unchanged.

Do others want to checkout this branch and try it?  I only tested it with a single Go project using go 1.11.4, so I'm not sure if there are lurking issues.

**Comment by peter-edge** [comment]
I checked out your branch and installed the binary, and tested it against github.com/uber/prototool, checked out outside of my `GOPATH`, and it works, FYI.

**Comment by lishunan246** [comment]
What if I am using go modules rather than vendored dependencies?
