### ISSUE TITLE
fmt.Print* should be checked for errors

### ISSUE THREAD

**Issue by egonk** [kisielk/errcheck#161]
Use case: command line apps that write actual data on stdout (not just logs), error on write indicates that the data processing should stop or report error on stderr. e.g. "cat"

> The exclude list is combined with an internal list for functions in the Go standard library that have an error return type but are documented to never return an error.

If my reading of stdlib docs & code is correct, fmt.Print* may return errors just like fmt.Fprint*(os.Stderr) for example.

Possible solutions

1. remove fmt.Print* from exclude list, cons: most correct (IMO) but annoyance for existing users
1. add -strict flag to remove fmt.Print* from exclude list and any such future cases
1. ...?

Thoughts?

**Comment by kisielk** [comment]
I think that in 99.99% of cases flagging missing error returns from `fmt.Printf` is a nuisance. For the other cases I think we could add a flag to discard to built-in list and only use explicitly-provided ignores.

**Comment by kisielk** [comment]
I propose calling the flag `-exclude-only`

**Comment by egonk** [comment]
> I think that in 99.99% of cases flagging missing error returns from `fmt.Printf` is a nuisance. For the other cases I think we could add a flag to discard to built-in list and only use explicitly-provided ignores.

Ok. Maintained built-in list is very useful otherwise, we use buffers a lot for example. I would prefer not to lose it :)

**Comment by kisielk** [comment]
Sure, but you could always copy it to your custom list

**Comment by egonk** [comment]
> Sure, but you could always copy it to your custom list

... or just vendor errcheck (I do that already) and change the default excludes so it's available out of the box, but that's what I wanted to avoid. I assumed there might be some interest in strict mode, but maybe there isn't. Instead of -strict flag, this would be more future-proof:
```
-builtin-excludes default (current behaviour, default)
-builtin-excludes strict
-builtin-excludes none
```

**Comment by dragonsinth** [comment]
I might argue that code writers should consider explicitly FPrint-ing to os.Stdout in these cases.

**Comment by amnonbc** [comment]
I recently had to fork this repo to stop it complaining about idiomatic code such as `defer resp.Body.Close()`

So I would urge the maintainers to avoid doing anything which increases false alarms,
and reduces the signal to noise ratio of the tool's output.

**Comment by dragonsinth** [comment]
We use a custom exclusion list for this, but generally speaking I think it'd be nice if defering io.Close() was ok by default.

**Comment by amnonbc** [comment]
> I think it'd be nice if defering io.Close() was ok by default.

feel free to use my patch https://github.com/amnonbc/errcheck/commit/cabf3a5aa199980ef2328c940d625989ea01a8b4

or even to use my fork https://github.com/amnonbc/errcheck
