### ISSUE TITLE
v1.2.0 enters infinite loop

### ISSUE THREAD

**Issue by RaduBerinde** [kisielk/errcheck#162]
Running `errcheck` on the CockroachDB code.

With errcheck v1.1.0:
```
$ time ~/roach2/bin/errcheck -exclude pkg/testutils/lint/testdata/errcheck_excludes.txt ./pkg/...

real	0m7.966s
user	0m45.962s
sys	0m5.611s
```

With v1.2.0, the same command doesn't finish (I waited 10 minutes). I also notice that a single core is pinned at 100% while it's running.

**Comment by RaduBerinde** [comment]
This was with go 1.10.

**Comment by RaduBerinde** [comment]
Looks like it works fine with go 1.11. Possibly related to https://github.com/golang/go/issues/29427

**Comment by echlebek** [comment]
Hmm, I guess we can chalk it up to that `x/tools` bug? We've since dropped support for that Go version, so I'll close this issue.
