### ISSUE TITLE
Enhancement: Prefix output lines with "errcheck: "

### ISSUE THREAD

**Issue by mcandre** [kisielk/errcheck#163]
When errcheck is run by itself, it is clear to the user how to react to the linter warnings. However, when errcheck is executed as part of a larger suite of linters, then seeing `hello.go:33:15:	defer f.Close()` is not enough context to know what the programmer should do with this line, because the context of which linter or warning type is missing.

Can we add a prefix like `errcheck:` to disambiguate this?

**Comment by dominikh** [comment]
It is the job of whatever is running multiple linters to prefix, suffix or otherwise annotate the output of individual linters to make it clear where output is coming from.

**Comment by mcandre** [comment]
👎 

No. In a large linter suite, with many thousands of warnings, and many Go novice users, it is entirely unclear what the current line output format means. You have to expect that the user will be very confused with the too-minimal output.

A simple `errcheck: ` prefix or `Error value not checked: `, or similar message, really goes a long way toward expressing what the problem is, and helping guide the user to the right answer in their code.
