### ISSUE TITLE
errcheck ignores applications

### ISSUE THREAD

**Issue by mcandre** [kisielk/errcheck#164]
errcheck does a good job enforcing error value checks for Go library code. However, errcheck currently ignores applications, such as net/http `ListenAndServe()` calls in `cmd/myserver/main.go`, which leads to risky code in Go binaries.

Please make sure that application code is scanned as well as library code.

**Comment by echlebek** [comment]
It should work just fine. Perhaps you need to `errcheck ./...`?

**Comment by dtcaciuc** [comment]
@mcandre Do you have an example of a repo we can try running errcheck on to reproduce the problem?
