### ISSUE TITLE
Migrating errcheck to go/analysis

### ISSUE THREAD

**Issue by vitarb** [kisielk/errcheck#165]
It looks like [x/tools/go/analysis](https://godoc.org/golang.org/x/tools/go/analysis) is [quickly becoming](https://godoc.org/golang.org/x/tools/go/analysis/passes) a new standard for writing static analysis in go. Being natively supported by tools like bazel's [nogo](https://github.com/bazelbuild/rules_go/blob/master/go/nogo.rst) it provides invaluable ability to unify all linters and perform static analysis at the build time.
errcheck being one of the most useful linters outside of go vet should greatly benefit from unification.

Are there any plans for doing this work or would you welcome contributions in this area?

**Comment by echlebek** [comment]
There aren't any plans to rewrite the tool. Contributions are welcome, but I have to wonder if integrating this library would lead to a wholly different program?

**Comment by dtcaciuc** [comment]
The package now provides `errcheck.Analyzer`; see README for short description and API stability disclaimer. This makes errcheck go/analysis-compatible while keeping the existing CLI unchanged.
