### ISSUE TITLE
Latest changes seem to have broken support for go 1.9, 1.10

### ISSUE THREAD

**Issue by Oscil8** [kisielk/errcheck#167]
I see errors like
```
error: failed to check packages: unsupported version of go: exit status 2: flag provided but not defined: -compiled
usage: list [-e] [-f format] [-json] [build flags] [packages]
Run 'go help list' for details.
make: *** [errcheck] Error 2
```

You probably want to either update the documentation or fix this.

**Comment by dominikh** [comment]
go/packages, a core dependency of errcheck, supports the last two versions of Go. We should update errcheck's documentation to reflect that.

**Comment by echlebek** [comment]
We've dropped support for these older Go versions.
