### ISSUE TITLE
Fail to install errorcheck with go get

### ISSUE THREAD

**Issue by Higan** [kisielk/errcheck#169]
After installing with `go get -u github.com/kisielk/errcheck`, I got the following info:
 
``` There is no tracking information for the current branch. Please specify which branch you want to merge with.```

and I found nothing in `\github.com\kisielk\errcheck`

**Comment by dtcaciuc** [comment]
Are you still getting this error? I ran this exact command and it completed successfully (go 1.14.6).

**Comment by dtcaciuc** [comment]
We closed this due to inactivity, but please let us know if you're still having issues.
