### ISSUE TITLE
Cannot handle packages which contains asm file

### ISSUE THREAD

**Issue by bobotu** [kisielk/errcheck#170]
Errcheck returns error when processing packge contains an empty asm file

```
error: failed to check packages: errors while loading package memdb: [memdb.s:12:35: expected ';', found 'EOF' memdb.s:12:35: expected 'IDENT', found 'EOF' memdb.s:12:35: expected 'package', found 'EOF' -: package ; expected memdb]
```

It seems like a bug in golang's tools, 
I have tried to use the latest version of `golang.org/x/tools` and this error goes away.

**Comment by echlebek** [comment]
We've upgraded the golang.org/x/tools dependency. Can you test with v1.3.0 and see if the issue resolves?

**Comment by echlebek** [comment]
Assuming this works now, please re-open if you find it's still a problem.
