### ISSUE TITLE
find errors ignored in type switches

### ISSUE THREAD

**Issue by ainar-g** [kisielk/errcheck#174]
<p>
I'm still not sure if this is closer to <code>errcheck</code> or to
<code>ineffassign</code>.  I often have this issue when working with
dynamically-typed APIs:
</p>

``` go
func h() (r *resp, err error) {
	err = f()
	if err != nil {
		return nil, err
	}

	// g returns interface{}.
	var v = g()
	switch v := v.(type) {
	case *resp:
		return v, nil
	case error:
		// Whoops!  Meant to say:
		//
		//   return nil, v
		return nil, err
	default:
		return nil, fmt.Errorf("bad type %T", v)
	}
}
```

<p>
I think that this is something <code>errcheck</code> (or
<code>ineffassign</code>?) should be able to find and mark.  It's very
close to doing something like:
</p>

``` go
var err2 = v.(error)
return nil, err
```

<p>
<a href="https://play.golang.org/p/Wk0r5DYQzsW">Full code link</a>.
<p>

**Comment by dtcaciuc** [comment]
I don't think it's possible to accurately determine whether it's a coding mistake or not. I've recently wrote some very similar looking code where I did exactly what you presented here, i.e. ignored a more closely scoped error and returned an error value computed elsewhere earlier.

**Comment by echlebek** [comment]
Agreed, I think there is too much ambiguity.
