### ISSUE TITLE
Integration with golangci-lint

### ISSUE THREAD

**Issue by SVilgelm** [kisielk/errcheck#184]
Hi,
The `golangci-lint` has an integration with `errcheck`, but is very outdated. it uses a fork of `errcheck` to export some functions. So would it be possible to include code such this: https://github.com/golangci/errcheck/blob/master/golangci/golangci.go to `errcheck` repo?
I'm ready to raise a PR
I want to get rid of fork and use the main repo instead.

Thank you!

**Comment by SVilgelm** [comment]
@kisielk Hi, could you please take a look at this?

**Comment by kisielk** [comment]
So just to be clear about your request, you're basically asking to make the internal/errcheck package available as a regular importable package?

**Comment by echlebek** [comment]
https://github.com/kisielk/errcheck/pull/185 makes the errcheck package available.

**Comment by SVilgelm** [comment]
@kisielk almost yes, if you can also change the `Checker.exclude` to be exported (`Checker.Exclude`), then golangci can use the `Checker` as a config 

@echlebek Thank you so much for the PR, could you also change `Checker.exclude` to `Checker.Exclude`?

**Comment by echlebek** [comment]
@SVilgelm just curious why you need this. Is there something you need to do that isn't covered by `AddExcludes()`?

**Comment by SVilgelm** [comment]
in golangci-lint we have a special structure: https://github.com/golangci/errcheck/blob/master/golangci/golangci.go#L22
so the users can configure errcheck in the global config file, the structure is totally same as the `Checker`, except `Exclude` field, so I think it would be easier to use the `Checker` instead of implementing own `Config`

**Comment by SVilgelm** [comment]
sorry, I was wrong, we actually don't need the Excludes to be exported, I can use `AddExcludes` function and will use the Checker directly here: https://github.com/golangci/golangci-lint/blob/master/pkg/golinters/errcheck.go#L107

**Comment by SVilgelm** [comment]
so, give me a couple of days, I will test the golangci-lint with the #185 PR

**Comment by echlebek** [comment]
@SVilgelm we've now published errcheck as a library. It does differ from what you were working with, but should meet your use case. If not, we'll do some follow-up work! Closing this now.
