### ISSUE TITLE
How does this differ from gosec G104 

### ISSUE THREAD

**Issue by chrisdlangton** [kisielk/errcheck#203]
If we already use https://github.com/securego/gosec like most teams do, how does errchecck help?

Is there a particular niche or set of edge cases missed by gosec that errcheck are better at identifying?

While I prefer gosec as it is easily integrated into a team with it's shared config file that handles project specific needs and all of the exceptions accepted and recorded so each team member doesn't get alert fatigue for nonesense the other team members have already triaged - so my question is **IF** errcheck has an added technical benefit that gosec does not provide, how do you currently (or plan to) support teams with multiple repos that have different accepted exception requirements, so that all members benefit when an issue is identified and an exception added for a good and agreed reason.

**Comment by kisielk** [comment]
Honestly I have no idea, I've never used gosec and am not familiar with it. As far as I can tell it was released to the public in 2016. I originally created errcheck as a weekend project for my own use and to learn the then-new go/types package back in 2013. I've never compared the feature set or tried to keep pace with any other tool, just maintain it based on user requests and to keep up with new Go versions. As far as technical benefits or any other requirements, please make your own evaluation.
