### ISSUE TITLE
zsh: command not found: errcheck

### ISSUE THREAD

**Issue by zhangm365** [kisielk/errcheck#223]
i have install the errcheck by the cmd:
```bash

go get -u github.com/kisielk/errcheck

```

Then, the error occur when it run the `errcheck` in directory.

**Comment by dtcaciuc** [comment]
Hello, could you please specify the Go version you're using and the error output of the errcheck command, if there is any?

**Comment by dtcaciuc** [comment]
Whoops, several days later I notice the error in the issue title 😅. Were your running errcheck with any arguments?

**Comment by dtcaciuc** [comment]
IIRC `go get` simply gets the sources but not compiles the program; can you try using `go install` per README and let us know if that works?

**Comment by kisielk** [comment]
Not a bug in errcheck
