### ISSUE TITLE
Support Build Tags

### ISSUE THREAD

**Issue by mjibson** [kisielk/errcheck#29]
App engine apps are difficult to configure for errcheck, and don't seem to work even when that is done. My `GOPATH` is set to: `/home/mjibson/go:/home/mjibson/go_appengine/goroot`. When running `errcheck github.com/mjibson/goread/goapp`, I get the following error:

error: failed to check package github.com/mjibson/goread/goapp: could not type check: /home/mjibson/go/src/github.com/mjibson/goread/goapp/admin.go:26:6: could not import github.com/MiniProfiler/go/miniprofiler_gae (/home/mjibson/go/src/github.com/MiniProfiler/go/miniprofiler_gae/miniprofiler_gae.go:26:2: could not import github.com/mjibson/appstats (/home/mjibson/go/src/github.com/mjibson/appstats/cost.go:6:2: could not import code.google.com/p/goprotobuf/proto (/home/mjibson/go/src/code.google.com/p/goprotobuf/proto/pointer_unsafe.go:90:42: cannot convert invalid operand to uintptr)))

That file (`pointer_unsafe.go`), has `+build !appengine` at the top, which could explain the error. I added this line to lib/util.go, after `ctx := build.Default`:

```ctx.BuildTags = append(ctx.BuildTags, "appengine")```

and the error didn't change. Do you have any other suggestions to get this to run?

**Comment by zimmski** [comment]
@mjibson Could you revisit your problem. The mentioned Go issue is already closed and errcheck supports build tags IMHO perfectly now.

**Comment by zimmski** [comment]
@kisielk: Could this be closed because the author is unresponsive?

**Comment by mjibson** [comment]
Fine with me to close it. I'm not planning on looking into it more.

On Sun, Oct 18, 2015 at 6:32 AM, Markus Zimmermann <notifications@github.com

**Comment by zimmski** [comment]
@mjibson: You just have to run `go get -u github.com/kisielk/errcheck` to update errcheck and its dependencies and then `errcheck github.com/mjibson/goread/goapp` which was you original usecase.
