### ISSUE TITLE
Can't use errcheck with ./...

### ISSUE THREAD

**Issue by aybabtme** [kisielk/errcheck#45]
Before #44, one could use errcheck like other go tools (`errcheck .` or `errcheck ./...`):

```
$ cd $GOPATH/src/github.com/kisielk/errcheck
$ git checkout 125d5c0d507709f2cb85970b145ae03621f6ffe5
$ go run *.go ./...
example/main.go:17:10	recover()     // UNCHECKED
example/main.go:20:15	defer recover() // UNCHECKED
example/main.go:26:3	a()     // UNCHECKED
example/main.go:30:3	b()        // UNCHECKED
example/main.go:35:5	x.a()     // UNCHECKED
example/main.go:40:7	y.t.a()     // UNCHECKED
example/main.go:44:9	m1["a"]()     // UNCHECKED
example/main.go:53:6	go a()    // UNCHECKED
example/main.go:54:9	defer a() // UNCHECKED
lib/errcheck.go:138:16	defer rd.Close()
exit status 1
```

After #44 :

```
$ git checkout master
$ git rev-parse --verify HEAD
6523a1db9b999015d645d53a36a450608d6111a2
$ go run *.go ./...
error: failed to check package: could not type check: import "./.": import relative to unknown directory
exit status 2
```

However, this way still works (fully qualified package name):

```
$ go run *.go github.com/kisielk/errcheck/...
github.com/kisielk/errcheck/example/main.go:17:10	recover()     // UNCHECKED
github.com/kisielk/errcheck/example/main.go:20:15	defer recover() // UNCHECKED
github.com/kisielk/errcheck/example/main.go:26:3	a()     // UNCHECKED
github.com/kisielk/errcheck/example/main.go:30:3	b()        // UNCHECKED
github.com/kisielk/errcheck/example/main.go:35:5	x.a()     // UNCHECKED
github.com/kisielk/errcheck/example/main.go:40:7	y.t.a()     // UNCHECKED
github.com/kisielk/errcheck/example/main.go:44:9	m1["a"]()     // UNCHECKED
github.com/kisielk/errcheck/example/main.go:53:6	go a()    // UNCHECKED
github.com/kisielk/errcheck/example/main.go:54:9	defer a() // UNCHECKED
exit status 1
```

**Comment by kisielk** [comment]
I'd really like to keep using go/loader. There's even a patch now https://groups.google.com/d/msg/golang-codereviews/ewN5tU-4IIQ/UnnYUJ_073IJ that's going to make it concurrent, so it should be even faster for large codebases.

**Comment by thieman** [comment]
I apologize if this is a stupid question, but is there any way currently to have `errcheck` check all of your project's modules with a single command? Or was `./..` the only way?

**Comment by kisielk** [comment]
`errcheck $(go list ./...)` works.

**Comment by shurcooL** [comment]
Can you use [`gotool.ImportPaths`](https://github.com/kisielk/gotool) to resolve input with import path patterns?

**Comment by shurcooL** [comment]
Hmm, I see you already use `gotool.ImportPaths`, so why does `errcheck $(go list ./...)` work but not `errcheck ./...`?

It seems that `go list ./...` converts the output import paths to full import paths, while `gotool.ImportPaths` returns relative import paths:

```
$ go list ./...
golang.org/x/tools/go/ssa
golang.org/x/tools/go/ssa/interp
golang.org/x/tools/go/ssa/ssautil
$ goe 'gotool.ImportPaths([]string{"./..."})'
([]string)([]string{
	(string)("./."),
	(string)("./interp"),
	(string)("./ssautil"),
})
```

Why doesn't `gotool.ImportPaths` return the same as `go list ./...` though? That seems unexpected.

**Comment by kisielk** [comment]
That's a good question. The go tool does something more. I haven't had time
to look deep in to it unfortunately.

On Sunday, January 18, 2015, Dmitri Shuralyov <notifications@github.com>
wrote:

> Hmm, I see you already use gotool.ImportPaths, so why does errcheck $(go
> list ./...) work but not errcheck ./...?
>
> It seems that go list ./... converts the output import paths to full
> import paths, while gotool.ImportPaths returns relative import paths:
>
> $ go list ./...golang.org/x/tools/go/ssagolang.org/x/tools/go/ssa/interpgolang.org/x/tools/go/ssa/ssautil
> $ goe 'gotool.ImportPaths([]string{"./..."})'
> ([]string)([]string{
>     (string)("./."),
>     (string)("./interp"),
>     (string)("./ssautil"),
> })
>
> Why doesn't gotool.ImportPaths return the same as go list ./... though?
> That seems unexpected.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kisielk/errcheck/issues/45#issuecomment-70417322>.
>


-- 
-K

**Comment by aybabtme** [comment]
yayyyy \o/
