### ISSUE TITLE
Add separate tests for -asserts being enabled or not

### ISSUE THREAD

**Issue by kisielk** [kisielk/errcheck#49]

**Comment by zimmski** [comment]
Is this for the error types? Can you please insert an example.

**Comment by kisielk** [comment]
`-types` got renamed to `-asserts`. The tests should check whether unchecked errors from assertions are reported when the flag is enabled, and that they are not when it's not.

**Comment by kisielk** [comment]
If you want to work on this it shouldn't be too hard to do, see https://github.com/kisielk/errcheck/blob/master/internal/errcheck/errcheck_test.go#L15
https://github.com/kisielk/errcheck/blob/master/internal/errcheck/errcheck_test.go#L52
https://github.com/kisielk/errcheck/blob/master/internal/errcheck/errcheck_test.go#L117
for how blank identifier checking is verified.

**Comment by zimmski** [comment]
OK you mean https://golang.org/ref/spec#Type_assertions ?

I am not too keen on doing that since I do not need it. However, you could add the label "help wanted" (or some other/new label) to this and other issues so that new/junior developers could be intrigued to do a PR.
