### ISSUE TITLE
Errcheck.go line 74

### ISSUE THREAD

**Issue by madhurranjan** [kisielk/errcheck#62]
github.com/kisielk/errcheck/internal/errcheck.go:74: unknown loader.Config field 'SourceImports' in struct literal

Sorry for not sending a merge request. I am still trying to figure out how to write code. But go the following error while installing vim-go

**Comment by shurcooL** [comment]
I can confirm. It's a breaking API change upstream in `golang.org/x/tools/go/loader`, commit https://github.com/golang/tools/commit/69db398fe0e69396984e3967724820c1f631e971.

Updating the code looks easy, just need to replace `SourceImports ` with `ImportFromBinary` and invert its value.
