### ISSUE TITLE
Ignore Test Files

### ISSUE THREAD

**Issue by benbjohnson** [kisielk/errcheck#66]
I recently ran an automated build for `boltdb/bolt` and received a bunch of `errcheck` errors that were not being shown before. It looks like `errcheck` is running against test files now. Is there anyway to set a flag to turn that off?

https://drone.io/github.com/boltdb/bolt/248

**Comment by kisielk** [comment]
That's because we're now using go/loader, which loads all _test files as well. There's no flag right now, but it wouldn't be hard to add one. I think in `internal/errcheck.go` on L107 we could filter out files ending in _test.go if the flag is set. Would that work for you?

**Comment by zimmski** [comment]
@benbjohnson: So you are ignoring errors in your tests?

@kisielk does this sound good to you?
- Add the flag "-ignoretests"
- Add the member "WithTests bool" to "Checker"
- Forward "WithTests" as argument to "FromArgs" of go/loader

**Comment by benbjohnson** [comment]
@zimmski Yeah, ignore what I was saying. :) I'll close the issue.

**Comment by kisielk** [comment]
I think having the flag is useful...  @zimmski that sounds reasonable to me
