### ISSUE TITLE
Error installing with go get

### ISSUE THREAD

**Issue by Thomasdezeeuw** [kisielk/errcheck#67]
When installing with `go get github.com/kisielk/errcheck` on Windows7 64 bit I get the following error: 

`..\..\kisielk\errcheck\internal\errcheck.go:75: unknown loader.Config field 'ImportFromBinary' in struct literal`

That is all the output.

**Comment by dominikh** [comment]
Use `go get -u`, you have an old version of a dependency lying around.

**Comment by kisielk** [comment]
What Dominik said, the `go.tools/go/types` API has changed a few times.

**Comment by Thomasdezeeuw** [comment]
I got a couple more error so for other people experiencing the same error you need to run `go get -u golang.org/x/tools/...`. I had some issues with the `golang.org/x/tools/astutil` package aswell, which moved to `golang.org/x/tools/ast/astutil` it seems.

**Comment by dominikh** [comment]
Using `go get -u github.com/kisielk/errcheck` should update all dependencies. You shouldn't need to update the individual dependencies by hand

**Comment by Thomasdezeeuw** [comment]
That didn't work for me, probably because the package moved

**Comment by shurcooL** [comment]
You might need to run `go get -u github.com/kisielk/errcheck` more than once if you get errors. This is a known bug/limitation in the go tool, see issue https://github.com/golang/go/issues/9224.
