### ISSUE TITLE
Change comma-delimited to arguments to be space-delimited

### ISSUE THREAD

**Issue by kisielk** [kisielk/errcheck#69]
To be more like the `go` tool.

@dominikh @shurcooL any thoughts about how we should do this? Do you think it's okay to just go ahead and change it or would it break too many things?

**Comment by dominikh** [comment]
Well, we could support both (and only document the space-delimited version), unless there could actually be arguments containing commas. That way, existing setups would continue to work, but new users would switch to the new way.

**Comment by kisielk** [comment]
so split on either a comma or space, whichever we see first?

**Comment by dominikh** [comment]
Right.

**Comment by zimmski** [comment]
This may be an unpopular suggestion but why not use go-flags to do the flag parsing? It would remove most of main.go and IMHO make it also clearer to read with its struct annotation.

**Comment by kisielk** [comment]
That is indeed unpopular :)

**Comment by shurcooL** [comment]
Why is that? I usually don't like those packages either because they're too complex (I use standard library's `flag` in my small personal projects). But I'm wondering what others' reasons are?

**Comment by zimmski** [comment]
- More external dependencies that need to be fetched and maintained
- None STD packages normally have no rules against API-breaking changes
are mine but the "flag" package is the one where I constantly think that it needs more functionality. Like the functionality errcheck implements which is also implemented in other major Go commands but it is simply not shared. The help/usage output is another functionality besides multi-value arguments which is constantly reimplemented.

**Comment by kisielk** [comment]
@shurcooL I want to avoid adding any more external dependencies. I don't mind doing a little bit more work to achieve that.
