### ISSUE TITLE
ignore underscored directories

### ISSUE THREAD

**Issue by jmhodges** [kisielk/errcheck#76]
Directories that begin with underscores (like _workspace) are ignored by most Go tools and the code inside them is not processed. This is used by godeps and other vendoring tools. Running `errcheck ./...` in a directory will have errcheck running against the code in Godeps/_workspace/src, which is undesirable in general.

**Comment by jmhodges** [comment]
(I, of course, solved this with use of -ignore, but it'd be nice to Just Work™ by default. Your call, though!)

**Comment by kisielk** [comment]
Hm, I just tried it and it seems to ignore them? maybe you have an old version of errcheck or `github.com/kisielk/gotool`?

**Comment by jmhodges** [comment]
Shoot, that seems to have been the problem. Sorry for the noise. I didn't realize I had already had it installed.

**Comment by kisielk** [comment]
No problem, easier than having to fix a bug :)
