### ISSUE TITLE
defer

### ISSUE THREAD

**Issue by powerman** [kisielk/errcheck#77]
Current version report lines like:
```go
defer client.Close()
```
Surely, error check is missing here, but that's how defer works and how all guidelines recommend to use it. Asking user to replace it with:
```go
defer func(){ _ = client.Close() }()
```
is probably overkill.

**Comment by kisielk** [comment]
That's why the package includes an ignore list. There are certainly cases where you wouldn't want to ignore the error returned from a deferred statement.

Granted, the ignore feature could probably be improved, suggestions are welcome (configuration file?)

**Comment by powerman** [comment]
I see. Maybe it make sense to add one more option?
```
-defer=false: if true, check for errors returned to defer
```

**Comment by kisielk** [comment]
I feel like that would probably be too broad, I think the whitelist approach is a better solution.

**Comment by dominikh** [comment]
See issue #55 for why ignoring all defers is a bad thing, and why there's a whole class of APIs where ignoring errors in defer leads to problems.

**Comment by amnonbc** [comment]
I have fixed this in my fork of errcheck
https://github.com/amnonbc/errcheck
