### ISSUE TITLE
Support for github.com/go-errors/errors

### ISSUE THREAD

**Issue by adrienkohlbecker** [kisielk/errcheck#80]
Hello,

Thanks for this useful tool, using it everyday. :)
We've started to use [go-errors](https://github.com/go-errors/errors) to easily get stacktraces when something goes wrong. It would be nice if errcheck could check for thoses as well.

I'm seeing an `isErrorType()` function in the code, would changing this be enough to work?
Basically, I would need to match `*errors.Error` as well as `error` in the function signatures.

Would it be acceptable to add a flag for additional error types?
Another option would be to check for the `error` interface rather than the concrete type, but I don't know if that's feasible.

Best

**Comment by kisielk** [comment]
So do you mean you have functions which specifically return *errors.Error instead of the error interface?

**Comment by adrienkohlbecker** [comment]
Yes

**Comment by kisielk** [comment]
Why not just return the error interface from those functions? It's pretty unusual to have code which returns concrete error types.

**Comment by adrienkohlbecker** [comment]
It's a way of enforcing that we have stack traces everywhere, all go errors are wrapped the first time they occur in our code. Like this:

```
	err := decoder.Decode(result)
	if err != nil {
		return errors.Wrap(err, 1)
	}
```

**Comment by kisielk** [comment]
Alright, unusual, but I can see why you'd do that. It shouldn't be hard to modify isErrorType to detect that.

**Comment by kisielk** [comment]
That should do it.

**Comment by adrienkohlbecker** [comment]
Wow, that was fast :)
Checking it out now

**Comment by adrienkohlbecker** [comment]
Hey, so I does not seem to work for me. Here is a test case 
It does work if I replace `*errors.Error` with `error`

```go
package main

import (
	"fmt"

	"github.com/go-errors/errors"
)

func someFunc() *errors.Error {
	return errors.Wrap(fmt.Errorf("some error"), 1)
}

func main() {
	someFunc()
}
```

**Comment by kisielk** [comment]
Okay, pointers were not correctly supported. That should be fixed with the above commit.

**Comment by kisielk** [comment]
Noticed one more thing wasn't being handled correctly in the case of functions with multiple returns. Fixed that as well.

**Comment by adrienkohlbecker** [comment]
Thanks a lot! That works for the test case above. 
I'm having another issue though: when there are multiple return parameters it does not work, here is a test case:
Again, it works when I put `error`

```go
package main

import (
	"fmt"

	"github.com/go-errors/errors"
)

func someFunc() (string, *errors.Error) {
	return "foobar", errors.Wrap(fmt.Errorf("some error"), 1)
}

func main() {
	someFunc()
}
```

**Comment by kisielk** [comment]
Did you pull again the second commit I added just above? It fixed exactly that issue.

**Comment by adrienkohlbecker** [comment]
Ah, my bad, I had to handle something in the middle of writing my comment and I did not refresh the page before submitting. 
Thank you again :)
