### ISSUE TITLE
Question related to ignore syntax

### ISSUE THREAD

**Issue by corsc** [kisielk/errcheck#81]
Sorry for the potentially dumb question.

I am trying to ignore a package but cannot seem to find the correct format.

I am running the following command in the `someone/somerepo` directory

`errcheck -asserts -ignorepkg 'github.com/someone/somerepo/fu/bar' ./...`

**Comment by kisielk** [comment]
Are you trying to avoid checking that package? `-ignorepkg` is used to ignore errors returned from calls to that package, not to exclude it from being checked if it's passed in the package list.

**Comment by corsc** [comment]
I see.  I was trying to avoid checking that package (its fully of generated code)

**Comment by shurcooL** [comment]
Just an observation, but it's actually easier for generated code to avoid `errcheck` issues because it's generated rather than hand-written, so being more verbose isn't as hard, isn't it?

**Comment by corsc** [comment]
Its not generated by my code :)  (go-bindata, thrift and ffjson generators or similar

**Comment by corsc** [comment]
Thanks.  I have recently discovered the gometalinter, so I think I will use that instead of the custom scripts, etc that I was maintaining to skip the directories
