### ISSUE TITLE
Failed to go get - unknown loader.Config field ImportFromBinary

### ISSUE THREAD

**Issue by kytrinyx** [kisielk/errcheck#83]
Installation failed with the following message:

```
go get github.com/kisielk/errcheck
# github.com/kisielk/errcheck/internal
../../code/go/src/github.com/kisielk/errcheck/internal/errcheck.go:91: unknown loader.Config field 'ImportFromBinary' in struct literal
```

I'm running Go on tip:

```
go version
go version devel +bc953b2 Tue Oct 6 03:18:17 2015 +0000 darwin/amd64
```

**Comment by zimmski** [comment]
Could you try a `go get -u -v github.com/kisielk/errcheck` This will update errcheck and its dependencies.

**Comment by kytrinyx** [comment]
Oh, wow, that would explain it. I didn't realize that I had an old version of this lying around. Sorry about that!

**Comment by kisielk** [comment]
It's more likely an old version of one of the dependencies. There's been a lot of churn in the location and API of the types and loader libs
