### ISSUE TITLE
allow for not scanning some packages

### ISSUE THREAD

**Issue by ryanking** [kisielk/errcheck#96]
The -ignorepkg flag can ignore the usage of certain packages. I have some packages that I'd like to skip scanning altogether (like test helpers).

**Comment by kisielk** [comment]
You can give errcheck a list of packages on the command line, its probably easiest to just give an explicit list of which packages you want checked.

**Comment by shurcooL** [comment]
You can do something popularized by Go 1.6 like `errcheck $(go list ./... | grep -v /vendor/ | grep -v something/else/you/dont/want)`.

**Comment by ryanking** [comment]
Great tip. thanks.
