### ISSUE TITLE
print file paths relative to pwd

### ISSUE THREAD

**Issue by ahmetalpbalkan** [kisielk/errcheck#98]
Most go tools (or go compiler itself) print file paths relative to pwd to the stdout so that for instance iTerm2 users on OS X can just Cmd+click on the filename:linenumber and it'll directly open up in their favorite IDE/editor.

There are currently two things preventing that:

1. paths are not relative to pwd
2. output is in format `path:lineno:nn` (I'm not sure what `nn` is but it should not have that segment in order Cmd+click to work)

**Comment by shurcooL** [comment]
The last `:nn`, is it the column number?

**Comment by ahmetalpbalkan** [comment]
@shurcooL haha that makes total sense now but at the same time not so much useful?

**Comment by kisielk** [comment]
How does the path being absolute keep tools from recognizing it as a path? That should make it easier if anything.

**Comment by dominikh** [comment]
The column number is useful and doesn't break tools that aren't dumb. 

We already have the `-abspath` flag to print absolute paths. However, I do agree that relative paths should be relative to the current working directory, not their import path, as it is now. That flaw is why we added `-abspath` originally. I didn't think to fix the actual problem and print correct relative paths.

**Comment by kisielk** [comment]
How about the above fix?

**Comment by ahmetalpbalkan** [comment]
@kisielk the fix works for me! thanks

> How does the path being absolute keep tools from recognizing it as a path?

it wasn't an abs path either, it was just a path relative to $GOPATH/src

**Comment by kisielk** [comment]
@ahmetalpbalkan yeah, I realized that was the case after Dominik's comment. I just had mine printing absolute paths by default via my editor.
